services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgre-versi
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5435:5432
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    volumes:
      - ./volume/postgresql:/var/lib/postgresql/data
