services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:192.168.3.44"
    volumes:
      - volume:/var/lib/pgadmin