services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgre
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    volumes:
      - ./volume/postgresql:/var/lib/postgresql/data
