services:
  # s3manager:
  #   container_name: s3manager
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - ENDPOINT=s3:9000
  #     - ACCESS_KEY_ID=s3manager
  #     - SECRET_ACCESS_KEY=s3manager
  #     - USE_SSL=false
  #   depends_on:
  #     - s3
  s3:
    container_name: s3
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ACCESS_KEY=s3manager
      - MINIO_SECRET_KEY=s3manager
      - MINIO_ADDRESS=0.0.0.0:9000
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:9001
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - ./volume:/data